### ISSUE TITLE
Socket connection keeps dropping

### ISSUE THREAD

**Issue by ngreis** [Juerd/Net-MQTT-Simple#7] opened 2019-06-20 13:11 UTC
Got your client to work, but i still cant get the kink out of the system.
Here is the log, the client, a zoneminder server connects and sends a publish command and then always gives a socket error and drops.
I think its related to your client either not correctly pinging the broker inside the 60 seconds keep alive or about the will message not beeing specified, wich always happens too.
Also you should set up a variable for the port, because using MQTT is on port 1883 but when using websockets its 1884. Dunno if that could be part of the problem also.
```
1561035374: Sending PINGRESP to rfb-1
1561035377: New connection from 192.168.1.5 on port 1883.
1561035377: New client connected from 192.168.1.5 as Net::MQTT::Simple[OVYPNCLXCH] (p2, c1, k60, u'iot').
1561035377: No will message specified.
1561035377: Sending CONNACK to Net::MQTT::Simple[OVYPNCLXCH] (0, 0)
1561035377: Received PUBLISH from Net::MQTT::Simple[OVYPNCLXCH] (d0, q0, r0, m0, 'zoneminder/1', ... (80 bytes))
1561035377: Socket error on client Net::MQTT::Simple[OVYPNCLXCH], disconnecting.
```

**Comment by Juerd** [comment] 2019-06-20 15:26
> Here is the log, the client, a zoneminder server connects and sends a publish command and then always gives a socket error and drops.

After how much time does it drop the connection?

> I think its related to your client either not correctly pinging the broker inside the 60 seconds keep alive

Is this a guess or have you actually already done some tracing to figure out that the keepalives are indeed not sent?

> or about the will message not beeing specified, wich always happens too.

I don't understand what this means. Can you go into more detail please?

> Also you should set up a variable for the port, because using MQTT is on port 1883 but when using websockets its 1884. 

Net::MQTT::Simple does not support websockets, but if you need to specify a port you can do so with a colon (`:`), like in:

    use Net::MQTT::Simple "mqtt.example.org:12345";

or when using the object oriented interface:

    use Net::MQTT::Simple;
    my $mqtt = Net::MQTT::Simple->new("mqtt.example.org:12345");

That you can specify a non-standard port is [documented](https://metacpan.org/pod/Net::MQTT::Simple), but not very clearly.

**Comment by ngreis** [comment] 2019-06-20 16:03
That log is the highest trace i can give you from the MQTT broker
The connection, publish and drops is done in a matter of seconds.

The zoneminder software, in this case zmNinja event notifications server, uses your package to send the MQTT, i might have misread that it was using websockets, or the error stating that is was a socket error might have induce me the wrong way.
It connects, publishes the camera alert state to a specific topic, and right after i have a _Socket error on client Net::MQTT::Simple[OVYPNCLXCH], disconnecting._, in the logs.
There is never a PINGREQS sent it he logs for the zoneminder server, ence one of my hunches.

The topic is created and updated as it should be, but i still get the Socket error right after the message beeing published.

**Comment by ngreis** [comment] 2019-06-20 16:03
Sorry wrong button.

**Comment by Juerd** [comment] 2019-06-20 16:09
> The connection, publish and drops is done in a matter of seconds.

Then I think we can rule out the keepalives as the cause of the issue.

> It connects, publishes the camera alert state to a specific topic, and right after i have a _Socket error on client Net::MQTT::Simple[OVYPNCLXCH], disconnecting._, in the logs.

It could be that the client disconnects because the object goes out of scope (or in case of the simple functional interface, the program has ended). In that case, this is the intended behaviour, and you can choose to do a graceful disconnection by calling the `disconnect` method explicitly.

Please share your code if you want me to look into it.

**Closed by Juerd** 2019-06-20 16:09 UTC

**Comment by ngreis** [comment] 2019-06-20 17:49
Its not my code, im am just configuring the interface, since zmNinja, uses your MQTT client to publish to MQTT servers.
So, this could be a expected behaviour, like just after delivering the pub it disconnects, you think the disconnection might just not be done the "proper" way, by invoquing the disconnect method.

**Comment by ngreis** [comment] 2019-06-20 18:59
Just to give out info.
The zoneminder was not using the disconnect method to clse the conn, causing the error.
I added the disconnect method to its script and did a PR on theire github.

Thx for the time 👍
